/* ============================================================
   Mil Palavras — per-word content (pronunciation, example, note)
   Keyed by the exact Portuguese string. Merged into the cards at
   boot: a card gets .ipa/.ex/.exE/.note/.noteE when its `p` matches.
   European Portuguese throughout. Added in batches, most-common first.
   Pronunciation: English respelling, CAPS = stressed syllable,
   nh→ny, lh→ly, final unstressed -e→uh, s→sh before a consonant/at end.
   ============================================================ */
window.MIL_CONTENT = {
  /* ---- Batch 1: greetings & expressions (0–14) ---- */
  "olá": { ipa:"o-LAH",
    ex:"Olá! Está tudo bem?", exE:"Hi! Is everything okay?",
    note:"A saudação mais neutra — serve para qualquer hora do dia.",
    noteE:"The most neutral greeting — it works at any time of day." },
  "tudo bem?": { ipa:"TOO-doo BENG",
    ex:"— Tudo bem? — Tudo, e tu?", exE:"— How's it going? — Good, and you?",
    note:"Serve de pergunta e de resposta: 'Tudo bem?' — 'Tudo bem.'",
    noteE:"Works as both the question and the answer: 'All good?' — 'All good.'" },
  "bom dia": { ipa:"bong DEE-ah",
    ex:"Bom dia! Um café, por favor.", exE:"Good morning! A coffee, please.",
    note:"Usa-se até ao meio-dia; depois passa a 'boa tarde'.",
    noteE:"Used until noon; after that it becomes 'boa tarde'." },
  "boa tarde": { ipa:"BOH-ah TAR-duh",
    ex:"Boa tarde, posso entrar?", exE:"Good afternoon, may I come in?",
    note:"Do meio-dia até ao pôr do sol.",
    noteE:"From noon until sunset." },
  "boa noite": { ipa:"BOH-ah NOY-tuh",
    ex:"Boa noite, até amanhã.", exE:"Good night, see you tomorrow.",
    note:"Serve para cumprimentar à noite e para despedir-se ao deitar.",
    noteE:"Used both to greet in the evening and to say goodnight." },
  "adeus": { ipa:"ah-DEH-oosh",
    ex:"Adeus, foi um prazer.", exE:"Goodbye, it was a pleasure.",
    note:"Mais definitivo do que 'até já' ou 'até logo'.",
    noteE:"More final than 'até já' or 'até logo' (see you soon / later)." },
  "até à próxima": { ipa:"ah-TEH ah PRO-see-mah",
    ex:"Obrigado por tudo, até à próxima!", exE:"Thanks for everything, until next time!",
    note:"Literalmente 'até à próxima (vez)'.",
    noteE:"Literally 'until the next (time)'." },
  "obrigado": { ipa:"oo-bree-GAH-doo",
    ex:"Obrigado pela ajuda.", exE:"Thank you for the help.",
    note:"Concorda com quem fala: um homem diz 'obrigado', uma mulher 'obrigada'.",
    noteE:"Agrees with the speaker: a man says 'obrigado', a woman 'obrigada'." },
  "obrigada": { ipa:"oo-bree-GAH-dah",
    ex:"Obrigada, é muito simpático.", exE:"Thank you, that's very kind.",
    note:"Forma feminina — dita por mulheres, seja com quem for.",
    noteE:"The feminine form — said by women, whoever they're speaking to." },
  "de nada": { ipa:"duh NAH-dah",
    ex:"— Obrigado! — De nada.", exE:"— Thank you! — You're welcome.",
    note:"Literalmente 'de nada'; também se ouve 'não tem de quê'.",
    noteE:"Literally 'of nothing'; you'll also hear 'não tem de quê'." },
  "com licença": { ipa:"kong lee-SEN-sah",
    ex:"Com licença, deixa-me passar.", exE:"Excuse me, let me get by.",
    note:"Para pedir passagem ou interromper; 'desculpe' é para pedir desculpa.",
    noteE:"To get past someone or interrupt; use 'desculpe' to apologise." },
  "desculpe": { ipa:"dush-KOOL-puh",
    ex:"Desculpe, onde fica a estação?", exE:"Excuse me, where is the station?",
    note:"Formal (você); a versão informal é 'desculpa'.",
    noteE:"Formal (você); the informal version is 'desculpa'." },
  "desculpa": { ipa:"dush-KOOL-pah",
    ex:"Desculpa o atraso!", exE:"Sorry I'm late!",
    note:"Informal (tu); com amigos e família.",
    noteE:"Informal (tu); with friends and family." },
  "não percebi": { ipa:"nowng per-suh-BEE",
    ex:"Desculpe, não percebi. Pode repetir?", exE:"Sorry, I didn't understand. Can you repeat?",
    note:"Em Portugal 'perceber' é 'entender'; 'não entendi' também serve.",
    noteE:"In Portugal 'perceber' means to understand; 'não entendi' works too." },
  "boa sorte!": { ipa:"BOH-ah SOR-tuh",
    ex:"Boa sorte no exame!", exE:"Good luck on the exam!",
    note:"'Sorte' é luck; 'ter sorte' = to be lucky.",
    noteE:"'Sorte' means luck; 'ter sorte' = to be lucky." },

  /* ---- Batch 1: common nouns (38–56) ---- */
  "o tempo": { ipa:"oo TENG-poo",
    ex:"Não tenho tempo hoje.", exE:"I don't have time today.",
    note:"Significa 'tempo' e 'clima': 'o tempo está bom'.",
    noteE:"Means both 'time' and 'weather': 'o tempo está bom' = the weather's nice." },
  "a vez": { ipa:"ah VESH",
    ex:"É a minha vez.", exE:"It's my turn.",
    note:"'Vez' = turn/occasion; 'uma vez' = once, 'às vezes' = sometimes.",
    noteE:"'Vez' = turn/occasion; 'uma vez' = once, 'às vezes' = sometimes." },
  "a coisa": { ipa:"ah KOY-zah",
    ex:"Que coisa estranha!", exE:"What a strange thing!",
    note:"Palavra-curinga para qualquer objeto ou assunto.",
    noteE:"A catch-all word for any object or matter." },
  "o homem": { ipa:"oo OH-meng",
    ex:"O homem à porta é o meu pai.", exE:"The man at the door is my father.",
    note:"Plural irregular: 'os homens' (OH-mengsh).",
    noteE:"Irregular plural: 'os homens'." },
  "a mulher": { ipa:"ah moo-LYER",
    ex:"A mulher dele é médica.", exE:"His wife is a doctor.",
    note:"Significa 'mulher' e 'esposa'; 'lh' soa como o 'lli' de 'million'.",
    noteE:"Means both 'woman' and 'wife'; 'lh' sounds like the 'lli' in 'million'." },
  "a casa": { ipa:"ah KAH-zah",
    ex:"Vou para casa.", exE:"I'm going home.",
    note:"'Em casa' = at home, 'para casa' = homewards — sem artigo nestas expressões.",
    noteE:"'Em casa' = at home, 'para casa' = homewards — no article in these set phrases." },
  "a vida": { ipa:"ah VEE-dah",
    ex:"Assim é a vida.", exE:"That's life.",
    note:"'Ganhar a vida' = to earn a living.",
    noteE:"'Ganhar a vida' = to earn a living." },
  "a morte": { ipa:"ah MOR-tuh",
    ex:"Foi uma questão de vida ou de morte.", exE:"It was a matter of life or death.",
    note:"Feminina, apesar de terminar em -e; o -e final soa 'uh'.",
    noteE:"Feminine, despite ending in -e; the final -e sounds like 'uh'." },
  "a pessoa": { ipa:"ah puh-SOH-ah",
    ex:"É uma boa pessoa.", exE:"He's a good person.",
    note:"Sempre feminina, mesmo para um homem: 'ele é uma pessoa simpática'.",
    noteE:"Always feminine, even for a man: 'ele é uma pessoa simpática'." },
  "o país": { ipa:"oo pah-EESH",
    ex:"Portugal é um país pequeno.", exE:"Portugal is a small country.",
    note:"Acento no 'í'; plural 'os países'. Não confundir com 'pais' (parents).",
    noteE:"Stress on the 'í'; plural 'os países'. Don't confuse with 'pais' (parents)." },
  "a cidade": { ipa:"ah see-DAH-duh",
    ex:"Lisboa é uma cidade linda.", exE:"Lisbon is a beautiful city.",
    note:"Feminina; palavras em -dade são sempre femininas (a verdade, a idade).",
    noteE:"Feminine; nouns ending in -dade are always feminine (a verdade, a idade)." },
  "o dia": { ipa:"oo DEE-ah",
    ex:"Bom dia! Que dia lindo.", exE:"Good morning! What a lovely day.",
    note:"Masculino, apesar de terminar em -a; 'todos os dias' = every day.",
    noteE:"Masculine, despite ending in -a; 'todos os dias' = every day." },
  "a noite": { ipa:"ah NOY-tuh",
    ex:"À noite fico em casa.", exE:"At night I stay home.",
    note:"'À noite' = at night; 'esta noite' = tonight.",
    noteE:"'À noite' = at night; 'esta noite' = tonight." },
  "a semana": { ipa:"ah suh-MAH-nah",
    ex:"Até para a semana!", exE:"See you next week!",
    note:"'Para a semana' = next week; 'fim de semana' = weekend.",
    noteE:"'Para a semana' = next week; 'fim de semana' = weekend." },
  "o ano": { ipa:"oo AH-noo",
    ex:"Tenho trinta anos.", exE:"I'm thirty years old.",
    note:"A idade diz-se com 'ter': 'ter … anos', não 'ser'.",
    noteE:"Age uses 'ter' (to have): 'ter … anos', not 'to be'." }
};
