/* ============================================================
   Mil Palavras — per-word content (pronunciation, example, note)
   Keyed by the exact Portuguese string. Merged into the cards at
   boot: a card gets .ipa/.ex/.exE/.note/.noteE when its `p` matches.
   European Portuguese throughout. Added in batches, most-common first.
   Pronunciation: English respelling. CAPITALS = the stressed syllable
   (single-syllable words stay lowercase). Nasal sounds are marked
   "(nasal)" — never a trailing g/ng. nh→ny, lh→ly, final -e→uh,
   s→sh before a consonant / at the end.
   ============================================================ */
window.MIL_CONTENT = {
  /* ---- Batch 1: greetings & expressions (0–14) ---- */
  "olá": { ipa:"o-LAH",
    ex:"Olá! Está tudo bem?", exE:"Hi! Is everything okay?",
    note:"A saudação mais neutra — serve para qualquer hora do dia.",
    noteE:"The most neutral greeting — it works at any time of day." },
  "tudo bem?": { ipa:"TOO-doo beh (nasal)",
    ex:"— Tudo bem? — Tudo, e tu?", exE:"— How's it going? — Good, and you?",
    note:"Serve de pergunta e de resposta: 'Tudo bem?' — 'Tudo bem.'",
    noteE:"Works as both the question and the answer: 'All good?' — 'All good.'" },
  "bom dia": { ipa:"bo (nasal) DEE-ah",
    ex:"Bom dia! Um café, por favor.", exE:"Good morning! A coffee, please.",
    note:"Usa-se até ao meio-dia; depois passa a 'boa tarde'.",
    noteE:"Used until noon; after that it becomes 'boa tarde'." },
  "boa tarde": { ipa:"BOH-ah TAR-duh",
    ex:"Boa tarde, posso entrar?", exE:"Good afternoon, may I come in?",
    note:"Do meio-dia até ao pôr do sol.",
    noteE:"From noon until sunset." },
  "boa noite": { ipa:"BOH-ah NOY-tuh",
    ex:"Boa noite, até amanhã.", exE:"Good night, see you tomorrow.",
    note:"Serve para cumprimentar à noite e para despedir-se ao deitar.",
    noteE:"Used both to greet in the evening and to say goodnight." },
  "adeus": { ipa:"ah-DEH-oosh",
    ex:"Adeus, foi um prazer.", exE:"Goodbye, it was a pleasure.",
    note:"Mais definitivo do que 'até já' ou 'até logo'.",
    noteE:"More final than 'até já' or 'até logo' (see you soon / later)." },
  "até à próxima": { ipa:"ah-TEH ah PRAW-see-mah",
    ex:"Obrigado por tudo, até à próxima!", exE:"Thanks for everything, until next time!",
    note:"Literalmente 'até à próxima (vez)'.",
    noteE:"Literally 'until the next (time)'." },
  "obrigado": { ipa:"oo-bree-GAH-doo",
    ex:"Obrigado pela ajuda.", exE:"Thank you for the help.",
    note:"Concorda com quem fala: um homem diz 'obrigado', uma mulher 'obrigada'.",
    noteE:"Agrees with the speaker: a man says 'obrigado', a woman 'obrigada'." },
  "obrigada": { ipa:"oo-bree-GAH-dah",
    ex:"Obrigada, é muito simpático.", exE:"Thank you, that's very kind.",
    note:"Forma feminina — dita por mulheres, seja com quem for.",
    noteE:"The feminine form — said by women, whoever they're speaking to." },
  "de nada": { ipa:"duh NAH-dah",
    ex:"— Obrigado! — De nada.", exE:"— Thank you! — You're welcome.",
    note:"Literalmente 'de nada'; também se ouve 'não tem de quê'.",
    noteE:"Literally 'of nothing'; you'll also hear 'não tem de quê'." },
  "com licença": { ipa:"co (nasal) lee-SEN-sah",
    ex:"Com licença, deixa-me passar.", exE:"Excuse me, let me get by.",
    note:"Para pedir passagem ou interromper; 'desculpe' é para pedir desculpa.",
    noteE:"To get past someone or interrupt; use 'desculpe' to apologise." },
  "desculpe": { ipa:"dush-KOOL-puh",
    ex:"Desculpe, onde fica a estação?", exE:"Excuse me, where is the station?",
    note:"Formal (você); a versão informal é 'desculpa'.",
    noteE:"Formal (você); the informal version is 'desculpa'." },
  "desculpa": { ipa:"dush-KOOL-pah",
    ex:"Desculpa o atraso!", exE:"Sorry I'm late!",
    note:"Informal (tu); com amigos e família.",
    noteE:"Informal (tu); with friends and family." },
  "não percebi": { ipa:"now (nasal) per-suh-BEE",
    ex:"Desculpe, não percebi. Pode repetir?", exE:"Sorry, I didn't understand. Can you repeat?",
    note:"Em Portugal 'perceber' é 'entender'; 'não entendi' também serve.",
    noteE:"In Portugal 'perceber' means to understand; 'não entendi' works too." },
  "boa sorte!": { ipa:"BOH-ah SOR-tuh",
    ex:"Boa sorte no exame!", exE:"Good luck on the exam!",
    note:"'Sorte' é luck; 'ter sorte' = to be lucky.",
    noteE:"'Sorte' means luck; 'ter sorte' = to be lucky." },

  /* ---- Batch 1: common nouns (38–56) ---- */
  "o tempo": { ipa:"oo TEH (nasal)-poo",
    ex:"Não tenho tempo hoje.", exE:"I don't have time today.",
    note:"Significa 'tempo' e 'clima': 'o tempo está bom'.",
    noteE:"Means both 'time' and 'weather': 'o tempo está bom' = the weather's nice." },
  "a vez": { ipa:"ah vehsh",
    ex:"É a minha vez.", exE:"It's my turn.",
    note:"'Vez' = turn/occasion; 'uma vez' = once, 'às vezes' = sometimes.",
    noteE:"'Vez' = turn/occasion; 'uma vez' = once, 'às vezes' = sometimes." },
  "a coisa": { ipa:"ah KOY-zah",
    ex:"Que coisa estranha!", exE:"What a strange thing!",
    note:"Palavra-curinga para qualquer objeto ou assunto.",
    noteE:"A catch-all word for any object or matter." },
  "o homem": { ipa:"oo OH-meh (nasal)",
    ex:"O homem à porta é o meu pai.", exE:"The man at the door is my father.",
    note:"Plural irregular: 'os homens'.",
    noteE:"Irregular plural: 'os homens'." },
  "a mulher": { ipa:"ah moo-LYER",
    ex:"A mulher dele é médica.", exE:"His wife is a doctor.",
    note:"Significa 'mulher' e 'esposa'; 'lh' soa como o 'lli' de 'million'.",
    noteE:"Means both 'woman' and 'wife'; 'lh' sounds like the 'lli' in 'million'." },
  "a casa": { ipa:"ah KAH-zah",
    ex:"Vou para casa.", exE:"I'm going home.",
    note:"'Em casa' = at home, 'para casa' = homewards — sem artigo nestas expressões.",
    noteE:"'Em casa' = at home, 'para casa' = homewards — no article in these set phrases." },
  "a vida": { ipa:"ah VEE-dah",
    ex:"Assim é a vida.", exE:"That's life.",
    note:"'Ganhar a vida' = to earn a living.",
    noteE:"'Ganhar a vida' = to earn a living." },
  "a morte": { ipa:"ah MOR-tuh",
    ex:"Foi uma questão de vida ou de morte.", exE:"It was a matter of life or death.",
    note:"Feminina, apesar de terminar em -e; o -e final soa 'uh'.",
    noteE:"Feminine, despite ending in -e; the final -e sounds like 'uh'." },
  "a pessoa": { ipa:"ah puh-SOH-ah",
    ex:"É uma boa pessoa.", exE:"He's a good person.",
    note:"Sempre feminina, mesmo para um homem: 'ele é uma pessoa simpática'.",
    noteE:"Always feminine, even for a man: 'ele é uma pessoa simpática'." },
  "o país": { ipa:"oo pah-EESH",
    ex:"Portugal é um país pequeno.", exE:"Portugal is a small country.",
    note:"Acento no 'í'; plural 'os países'. Não confundir com 'pais' (parents).",
    noteE:"Stress on the 'í'; plural 'os países'. Don't confuse with 'pais' (parents)." },
  "a cidade": { ipa:"ah see-DAH-duh",
    ex:"Lisboa é uma cidade linda.", exE:"Lisbon is a beautiful city.",
    note:"Feminina; palavras em -dade são sempre femininas (a verdade, a idade).",
    noteE:"Feminine; nouns ending in -dade are always feminine (a verdade, a idade)." },
  "o dia": { ipa:"oo DEE-ah",
    ex:"Bom dia! Que dia lindo.", exE:"Good morning! What a lovely day.",
    note:"Masculino, apesar de terminar em -a; 'todos os dias' = every day.",
    noteE:"Masculine, despite ending in -a; 'todos os dias' = every day." },
  "a noite": { ipa:"ah NOY-tuh",
    ex:"À noite fico em casa.", exE:"At night I stay home.",
    note:"'À noite' = at night; 'esta noite' = tonight.",
    noteE:"'À noite' = at night; 'esta noite' = tonight." },
  "a semana": { ipa:"ah suh-MAH-nah",
    ex:"Até para a semana!", exE:"See you next week!",
    note:"'Para a semana' = next week; 'fim de semana' = weekend.",
    noteE:"'Para a semana' = next week; 'fim de semana' = weekend." },
  "o ano": { ipa:"oo AH-noo",
    ex:"Tenho trinta anos.", exE:"I'm thirty years old.",
    note:"A idade diz-se com 'ter': 'ter … anos', não 'ser'.",
    noteE:"Age uses 'ter' (to have): 'ter … anos', not 'to be'." },

  /* ---- Batch 2: the essential verbs ---- */
  "ser": { ipa:"sehr",
    ex:"Eu sou português.", exE:"I am Portuguese.",
    note:"Ser é permanente: identidade, origem, profissão. Compara com 'estar'.",
    noteE:"Ser is for permanent things — identity, origin, profession. Contrast with 'estar'." },
  "ter": { ipa:"tehr",
    ex:"Tenho dois irmãos.", exE:"I have two brothers.",
    note:"Também exprime idade e sensações: 'ter fome', 'ter 30 anos'.",
    noteE:"Also used for age and feelings: 'ter fome' (be hungry), 'ter 30 anos' (be 30)." },
  "estar": { ipa:"ish-TAR",
    ex:"Estou cansado hoje.", exE:"I'm tired today.",
    note:"Estar é temporário: estados e localização. 'Estou em casa.'",
    noteE:"Estar is for temporary states and location: 'Estou em casa' = I'm at home." },
  "poder": { ipa:"poo-DER",
    ex:"Posso entrar?", exE:"May I come in?",
    note:"'Posso?' = may I? — pedido educado do dia a dia.",
    noteE:"'Posso?' = may I? — an everyday polite request." },
  "fazer": { ipa:"fah-ZER",
    ex:"O que fazes ao fim de semana?", exE:"What do you do at the weekend?",
    note:"Irregular; também para o tempo: 'faz frio' = it's cold.",
    noteE:"Irregular; also used for weather: 'faz frio' = it's cold." },
  "ir": { ipa:"eer",
    ex:"Vou ao mercado.", exE:"I'm going to the market.",
    note:"'Ir + infinitivo' forma o futuro próximo: 'vou comer'.",
    noteE:"'Ir + infinitive' makes the near future: 'vou comer' = I'm going to eat." },
  "dizer": { ipa:"dee-ZER",
    ex:"Diz-me a verdade.", exE:"Tell me the truth.",
    note:"Irregular: 'digo, dizes, diz…'.",
    noteE:"Irregular: 'digo, dizes, diz…'." },
  "dar": { ipa:"dar",
    ex:"Dá-me um copo de água.", exE:"Give me a glass of water.",
    note:"Em muitas expressões: 'dar um passeio', 'dar-se bem'.",
    noteE:"In many phrases: 'dar um passeio' (take a walk), 'dar-se bem' (get along)." },
  "ver": { ipa:"vehr",
    ex:"Vejo-te amanhã.", exE:"I'll see you tomorrow.",
    note:"Ver = see/watch; 'olhar' = to look at.",
    noteE:"Ver = to see/watch; 'olhar' = to look at." },
  "saber": { ipa:"sah-BER",
    ex:"Sabes onde fica?", exE:"Do you know where it is?",
    note:"Saber = saber factos; 'conhecer' = conhecer pessoas/lugares.",
    noteE:"Saber = to know facts; 'conhecer' = to know people/places." },
  "querer": { ipa:"kuh-RER",
    ex:"Quero um café, por favor.", exE:"I want a coffee, please.",
    note:"'Queria…' (imperfeito) soa mais educado: 'queria um café'.",
    noteE:"'Queria…' (imperfect) sounds more polite: 'I'd like a coffee'." },
  "ficar": { ipa:"fee-KAR",
    ex:"Fico em casa esta noite.", exE:"I'm staying home tonight.",
    note:"Faz o trabalho de três verbos: stay, become e be located.",
    noteE:"Does the work of three English verbs: to stay, to become, and to be located." },
  "vir": { ipa:"veer",
    ex:"Vem cá!", exE:"Come here!",
    note:"Irregular; não confundir com 'ver' (to see).",
    noteE:"Irregular; don't confuse with 'ver' (to see)." },
  "falar": { ipa:"fah-LAR",
    ex:"Falas inglês?", exE:"Do you speak English?",
    note:"Regular -ar; 'falar com' = to talk to.",
    noteE:"Regular -ar verb; 'falar com' = to talk to." },

  /* ---- Batch 2: family & more common nouns ---- */
  "a família": { ipa:"fah-MEE-lee-ah",
    ex:"A minha família é grande.", exE:"My family is big.",
    note:"Acento no 'í': fa-MÍ-lia.",
    noteE:"Stress on the 'í': fah-MEE-lee-ah." },
  "o pai": { ipa:"oo pie",
    ex:"O meu pai chama-se João.", exE:"My father's name is João.",
    note:"Plural 'os pais' = parents (não só 'fathers').",
    noteE:"Plural 'os pais' means 'parents', not just 'fathers'." },
  "a mãe": { ipa:"ah my (nasal)",
    ex:"A minha mãe é professora.", exE:"My mother is a teacher.",
    note:"Vogal nasal; plural 'as mães'.",
    noteE:"Nasal vowel; plural 'as mães'." },
  "o filho": { ipa:"oo FEE-lyoo",
    ex:"Eles têm um filho.", exE:"They have a son.",
    note:"'Os filhos' pode significar 'children' (filhos e filhas).",
    noteE:"'Os filhos' can mean 'children' (sons and daughters together)." },
  "a filha": { ipa:"ah FEE-lyah",
    ex:"A filha deles estuda medicina.", exE:"Their daughter studies medicine.",
    note:"'lh' soa como o 'lli' de 'million'.",
    noteE:"'lh' sounds like the 'lli' in 'million'." },
  "o irmão": { ipa:"oo eer-MOW (nasal)",
    ex:"O meu irmão é mais novo.", exE:"My brother is younger.",
    note:"Plural irregular 'os irmãos'; 'mais novo' = younger.",
    noteE:"Irregular plural 'os irmãos'; 'mais novo' = younger." },
  "a irmã": { ipa:"ah eer-MA (nasal)",
    ex:"Tenho uma irmã.", exE:"I have a sister.",
    note:"Feminino de 'irmão'; plural 'as irmãs'.",
    noteE:"Feminine of 'irmão'; plural 'as irmãs'." },
  "o trabalho": { ipa:"oo trah-BAH-lyoo",
    ex:"Vou para o trabalho.", exE:"I'm going to work.",
    note:"'Trabalho' = work/job; o verbo é 'trabalhar'.",
    noteE:"'Trabalho' = work/job; the verb is 'trabalhar'." },
  "o mundo": { ipa:"oo MOON-doo",
    ex:"É o melhor do mundo.", exE:"It's the best in the world.",
    note:"Em Portugal 'toda a gente' = everyone, não 'todo o mundo'.",
    noteE:"In Portugal 'everyone' is 'toda a gente', not 'todo o mundo'." },
  "o nome": { ipa:"oo NOH-muh",
    ex:"Qual é o teu nome?", exE:"What's your name?",
    note:"Mais comum: 'como te chamas?'.",
    noteE:"More common: 'como te chamas?' = what's your name?" },
  "o problema": { ipa:"oo proo-BLEH-mah",
    ex:"Não há problema.", exE:"No problem.",
    note:"Masculino apesar do -a (vem do grego): 'o problema'.",
    noteE:"Masculine despite the -a (it's from Greek): 'o problema'." },

  /* ---- Batch 3: more nouns, verbs & adjectives ---- */
  "a água": { ipa:"AH-gwah",
    ex:"Um copo de água, por favor.", exE:"A glass of water, please.",
    note:"Acento no primeiro 'á'; feminina.", noteE:"Stress on the first 'á'; feminine." },
  "a comida": { ipa:"koo-MEE-dah",
    ex:"A comida portuguesa é deliciosa.", exE:"Portuguese food is delicious.",
    note:"Do verbo 'comer'; 'comida' = food/meal.", noteE:"From the verb 'comer' (to eat); means food/meal." },
  "a palavra": { ipa:"pah-LAH-vrah",
    ex:"Não percebi a última palavra.", exE:"I didn't catch the last word.",
    note:"É o nome da aplicação: Mil Palavras.", noteE:"It's the app's name: Mil Palavras (a thousand words)." },
  "o facto": { ipa:"FAH-too",
    ex:"De facto, tens razão.", exE:"In fact, you're right.",
    note:"Em Portugal escreve-se 'facto' (com c); no Brasil, 'fato'. 'De facto' = in fact.",
    noteE:"In Portugal it's spelled 'facto' (with a c); in Brazil 'fato'. 'De facto' = in fact." },
  "a história": { ipa:"ish-TAW-ree-ah",
    ex:"Conta-me uma história.", exE:"Tell me a story.",
    note:"Significa 'history' e 'story'; a grafia 'estória' não se usa em Portugal.",
    noteE:"Means both 'history' and 'story'; the spelling 'estória' isn't used in Portugal." },
  "a guerra": { ipa:"GEH-rrah",
    ex:"A guerra acabou.", exE:"The war is over.",
    note:"'gu' antes de 'e' soa como o 'g' de 'get'.", noteE:"'gu' before 'e' sounds like the hard g in 'get'." },
  "a paz": { ipa:"pash",
    ex:"Queremos paz.", exE:"We want peace.",
    note:"Final '-z' soa 'sh'; rima com 'faz'.", noteE:"Final '-z' sounds 'sh'; it rhymes with 'faz'." },
  "o número": { ipa:"NOO-muh-roo",
    ex:"Qual é o teu número de telefone?", exE:"What's your phone number?",
    note:"Acento no 'ú': NÚ-me-ro.", noteE:"Stress on the 'ú': NOO-muh-roo." },
  "o fim": { ipa:"fee (nasal)",
    ex:"Até ao fim de semana!", exE:"See you at the weekend!",
    note:"Nasal; 'fim de semana' = weekend; 'ao fim de' = at the end of.",
    noteE:"Nasal; 'fim de semana' = weekend; 'ao fim de' = at the end of." },
  "sair": { ipa:"sah-EER",
    ex:"Vou sair esta noite.", exE:"I'm going out tonight.",
    note:"Sair = to go out/leave; o oposto de 'entrar'.", noteE:"Sair = to go out/leave; the opposite of 'entrar'." },
  "voltar": { ipa:"vol-TAR",
    ex:"Volto já.", exE:"I'll be right back.",
    note:"'Voltar' = to come/go back; 'volto já' = back in a moment.", noteE:"'Voltar' = to come/go back; 'volto já' = back in a moment." },
  "conseguir": { ipa:"ko (nasal)-suh-GEER",
    ex:"Não consigo abrir a porta.", exE:"I can't open the door.",
    note:"= to manage / be able to; irregular: 'consigo, consegues'.", noteE:"= to manage / be able to; irregular: 'consigo, consegues'." },
  "achar": { ipa:"ah-SHAR",
    ex:"Acho que sim.", exE:"I think so.",
    note:"'Achar que' = to think that (opinião); 'acho que sim/não'.", noteE:"'Achar que' = to think that (opinion); 'acho que sim' = I think so." },
  "sentir": { ipa:"se (nasal)-TEER",
    ex:"Sinto-me bem.", exE:"I feel well.",
    note:"'Sentir-se' + adjetivo = to feel …; irregular: 'sinto'.", noteE:"'Sentir-se' + adjective = to feel …; irregular: 'sinto'." },
  "conhecer": { ipa:"koo-nyuh-SER",
    ex:"Conheces Lisboa?", exE:"Do you know Lisbon?",
    note:"Conhecer = conhecer pessoas/lugares; 'saber' = saber factos.", noteE:"Conhecer = to know people/places; 'saber' = to know facts." },
  "viver": { ipa:"vee-VER",
    ex:"Vivo em Lisboa.", exE:"I live in Lisbon.",
    note:"'Viver' = to live; 'morar' = to reside (mais específico).", noteE:"'Viver' = to live; 'morar' = to reside (more specific)." },
  "ouvir": { ipa:"oh-VEER",
    ex:"Ouves música?", exE:"Do you listen to music?",
    note:"Ouvir = to hear/listen; irregular: 'ouço, ouves'.", noteE:"Ouvir = to hear/listen; irregular: 'ouço, ouves'." },
  "pôr": { ipa:"por",
    ex:"Põe a mesa, por favor.", exE:"Set the table, please.",
    note:"Leva acento circunflexo para o distinguir de 'por' (by/for). Irregular.",
    noteE:"Written with a circumflex (pôr) to tell it apart from 'por' (by/for). Irregular." },
  "continuar": { ipa:"ko (nasal)-tee-noo-AR",
    ex:"Continua em frente.", exE:"Carry straight on.",
    note:"'Continuar a + infinitivo' = to keep doing something.", noteE:"'Continuar a + infinitive' = to keep doing something." },
  "bom": { ipa:"bo (nasal)",
    ex:"Está um bom dia.", exE:"It's a nice day.",
    note:"Masculino; feminino 'boa'. Vogal nasal.", noteE:"Masculine; feminine 'boa'. Nasal vowel." },
  "mau": { ipa:"mow",
    ex:"Faz mau tempo.", exE:"The weather's bad.",
    note:"Masculino; feminino 'má'. Não confundir com 'mal' (advérbio, = badly).",
    noteE:"Masculine; feminine 'má'. Don't confuse with 'mal' (adverb, = badly)." },
  "melhor": { ipa:"muh-LYOR",
    ex:"Este é melhor.", exE:"This one is better.",
    note:"Comparativo de 'bom'; 'o melhor' = the best. 'lh' = 'ly'.", noteE:"Comparative of 'bom'; 'o melhor' = the best. 'lh' = 'ly'." },
  "grande": { ipa:"GRA (nasal)-duh",
    ex:"Uma casa grande.", exE:"A big house.",
    note:"Invariável no género: 'um homem grande', 'uma casa grande'.", noteE:"Same for both genders: 'um homem grande', 'uma casa grande'." },
  "pequeno": { ipa:"puh-KEH-noo",
    ex:"Um café pequeno.", exE:"A small coffee.",
    note:"Feminino 'pequena'; 'pequeno-almoço' = breakfast (em Portugal).", noteE:"Feminine 'pequena'; 'pequeno-almoço' = breakfast (in Portugal)." },
  "bonito": { ipa:"boo-NEE-too",
    ex:"Que vista bonita!", exE:"What a lovely view!",
    note:"Feminino 'bonita'; sinónimo de 'lindo'.", noteE:"Feminine 'bonita'; a synonym of 'lindo'." }
};
